noranbear/how-about-e-medicine

src/main/java/com/multi/biz/MymediBiz.java, src/main/java/com/multi/frame/Biz.java, src/main/java/com/multi/mapper/MymediMapper.java, src/main/java/com/multi/mybatis/mymedi.xml, src/main/java/com/multi/vo/MymediVo.java, src/test/java/com/multi/MymediDeleteTests.java, src/test/java/com/multi/MymediInsertTests.java, src/test/java/com/multi/MymediSelectAllTests.java, src/test/java/com/multi/MymediSelectTests.java, src/test/java/com/multi/MymediUpdateTests.java
- mymedi 테이블 CRUD 구축 
*Bug나 문제가 발견되었다면 언급*
- frame pckg: Biz.java
- vo pckg: MymediVo.java
- mybatis pckg: mymedi.xml
- mapper pckg: MymediMapper.java
- biz pckg: MymediBiz.java
- test pckg
- MymediInsertTests.java
- MymediDeleteTests.java
- MymediUpdateTests.java
- MymediSelectTests.java
- MymediSelectAllTests.java
- Insert (완료)
- Delete (완료)
- Update (완료)
- Select (완료)
- SelectAll 완료)
---
관련 Issue: #2 
co-authored-by: qwaszx357
=>  ✨✅ CRUD Mymedi 구축

src/main/java/com/multi/controller/AJAXController.java, src/main/java/com/multi/controller/MainController.java, src/main/java/com/multi/restapi/DataAPI.java, src/main/resources/templates/index.html, src/test/java/com/multi/api/DataTest.java, src/test/java/com/multi/api/OCRBoxTest.java, src/test/java/com/multi/api/OCREnvelopeTest.java
- 공공 데이터 API-약정보 작동 및 연동 테스트
- 메인 페이지에서 공공 데이터 API-약정보 사용 가능한지 테스트
*Bug나 문제가 발견되었다면 언급*
- DataAPI.java
- 공공 데이터 API-약정보 연동
- `dataapi` 메소드 생성
- DataTest.java
-  `dataapi` 메소드 테스트
- MainController.java
- `index.html` 연결 
- AJAXController.java
- dataget 메소드 생성
- `index`에서 받은 약이름 등으로 `DataAPI`를 이용해 해당 정보를 가져와 준다.  
- index.html
- 검색창 생성 (input 받기)
- `dataget` 연결 
- DataAPI.java
- `dataapi` 메소드 정상 작동 확인 
- 메인 페이지 연동 결과 페이지
---
관련 Issue: #13
=> ✨✅ 공공 데이터 API-약정보 작동 테스트 완료 및 메인 화면에서 사용 테스트 완료

src/main/resources/templates/index.html
- 메인 페이지에 유저로고 추가해서 로그인 창을 구현하기 위해
*Bug나 문제가 발견되었다면 언급*
- 메인 페이지 왼쪽 사이드 바에 유저로고 추가
---
관련 Issue: #17
=> 💄 메인 페이지 사이드 바에 유저로고 추가

src/main/resources/templates/signup.html
회원가입시 입력사항 추가
테스트 유무
---
관련 Issue: #19
=> 💄 add signup page

src/main/java/com/multi/controller/MainController.java, src/main/resources/templates/index.html, src/main/resources/templates/signin.html
- 로그인 기능 추가
(스크린샷 추가 가능)
- 로그인 제약 사항
- id, pwd 일치 확인
- 로그인, 로그아웃 기능
테스트 유무
---
관련 Issue:
#41
=> ⚡️ signin 기능 구현

src/main/resources/templates/medidetail.html
(스크린샷 추가 가능)
약 디테일 페이지 화면 디자인 변경
부트스트랩 적용하여 메뉴 페이지 변경
테스트 유무
---
관련 Issue: #22
=> 💄 약 디테일 페이지 화면 디자인 변경

src/main/java/com/multi/biz/SlistBiz.java, src/main/java/com/multi/biz/SmediBiz.java, src/main/java/com/multi/mapper/SlistMapper.java, src/main/java/com/multi/mapper/SmediMapper.java, src/main/java/com/multi/mybatis/slistmapper.xml, src/main/java/com/multi/mybatis/smedimapper.xml, src/main/java/com/multi/mybatis/usersmapper.xml, src/main/java/com/multi/vo/SlistVo.java, src/main/java/com/multi/vo/SmediVo.java, src/main/java/com/multi/vo/UsersVo.java, src/test/java/com/multi/slist/SlistDeleteTests.java, src/test/java/com/multi/slist/SlistInsertTests.java, src/test/java/com/multi/slist/SlistSelectAllTests.java, src/test/java/com/multi/slist/SlistSelectTests.java, src/test/java/com/multi/slist/SlistUpdateTests.java, src/test/java/com/multi/smedi/SmediDeleteTests.java, src/test/java/com/multi/smedi/SmediInsertTests.java, src/test/java/com/multi/smedi/SmediSelectAllTests.java, src/test/java/com/multi/smedi/SmediSelectTests.java, src/test/java/com/multi/smedi/SmediUpdateTests.java, src/test/java/com/multi/users/UsersInsertTests.java, src/test/java/com/multi/users/UsersUpdateTests.java
- DB V5 변경에 따른 CRUD 수정
- users
- UsersVo
- usersmapper.xml
- 테스트
- UsersInserTests
- UsersUpdateTests
- slist CRUD 생성 및 테스트
- smedi CRUD 생성 및 테스트
---
관련 Issue: #68
=> 📦 ✅ DB V5 변경 내역 CRUD 적용 및 테스트 완료

src/main/java/com/multi/controller/MainController.java, src/main/resources/static/assets/ezocss/plistcss.css, src/main/resources/templates/index.html, src/main/resources/templates/plist.html
plist 페이지 구현
(스크린샷 추가 가능)
- 복용 중 처방내역
- 복용 완료 처방내역
테스트 유무
---
관련 Issue:
#28 #32
=> 💄 plist 페이지 구현

src/main/resources/templates/medidetail.html
(스크린샷 추가 가능)
약 디테일 페이지 화면 재구성
내 약 리스트에 담기 버튼 클릭 시 로그인 메시지 스낵바 구현
테스트 유무
---
관련 Issue:
#22
=> 💄 약 디테일 화면 구성 및 스낵바 구현

src/main/java/com/multi/biz/PlistBiz.java, src/main/java/com/multi/controller/MainController.java, src/main/java/com/multi/mapper/PlistMapper.java, src/main/java/com/multi/mybatis/plistmapper.xml, src/main/java/com/multi/vo/PlistVo.java, src/main/resources/static/assets/ezocss/plistcss.css, src/main/resources/templates/index.html, src/main/resources/templates/plist.html, src/test/java/com/multi/plist/PlistSelect_EndTests.java, src/test/java/com/multi/plist/PlistSelect_IngTests.java
- 처방내역 페이지 출력 기능 구현
(스크린샷 추가 가능)
- 복용중인 약 출력
- 복용 완료 액 출력
- 추가 버튼 클릭 시 추가 페이지로 이동
테스트 유무
- select_ing, select_end 테스트 완료
---
관련 Issue:
#48
=> 📦 처방내역 출력기능 구현

src/main/java/com/multi/biz/MymediBiz.java, src/main/java/com/multi/controller/MainController.java, src/main/java/com/multi/mapper/MymediMapper.java, src/main/java/com/multi/mybatis/mymedimapper.xml, src/main/resources/templates/mymedi.html
내약리스트 기능구현
테스트 유무
---
관련 Issue: #47
=> 📦 내약리스트 기능 구현

src/main/java/com/multi/controller/MainController.java, src/main/resources/static/assets/ezocss/centercss.css, src/main/resources/static/assets/ezocss/searchresult.css, src/main/resources/templates/center.html, src/main/resources/templates/index.html, src/main/resources/templates/searchresult.html
- 메인 페이지에서 기존의 검색 테이블 삭제 후 새로운 검색 결과 페이지 구현
(스크린샷 추가 가능)
- 검색 결과 테이블 생성
- 이미지, 제품명, 업체명, 효능효과 출력
테스트 유무
---
관련 Issue:
#20
=> 💄 검색 결과 페이지 구현

src/main/resources/templates/center.html, src/main/resources/templates/dashboard.html, src/main/resources/templates/index.html, src/main/resources/templates/medidetail.html, src/main/resources/templates/mymedi.html, src/main/resources/templates/pdetail.html, src/main/resources/templates/plist.html, src/main/resources/templates/profile.html
- 페이지 하단에 footer 고정
(스크린샷 추가 가능)
- index.html에 footer 추가
- 다른 html에서 footer 삭제
테스트 유무
---
관련 Issue:
#78
=> 💄 footer 고정

src/main/resources/templates/center.html
OCR 이미지 업로드 창 구현
(스크린샷 추가 가능)
- 메인 페이지에 있는 카메라 아이콘을 클릭 시, modal 창이 나온다.
- 이미지 드래그 창
- 이미지 링크 input 
- 이미지 업로드 기능 구현
- 검색 버튼
테스트 유무
- 파일 업로드 테스트, 프리뷰 테스트 완료
---
관련 Issue: #26
=> 💄 OCR 이미지 업로드 창 구현

src/main/java/com/multi/controller/MainController.java, src/main/resources/templates/profile.html
프로필 화면 구현
테스트 유무
---
관련 Issue: #70
=> 💄 프로필 화면 구현

src/main/java/com/multi/controller/MainController.java, src/main/resources/templates/signin.html, src/main/resources/templates/signup.html
- 로그인, 회원가입 페이지 헤더 수정
(스크린샷 추가 가능)
- signup 페이지 센터 삭제
- 로그인, 회원가입 페이지 헤더 수정
- 헤더 링크 연결
테스트 유무
---
관련 Issue:
#97
=> 📦 signin, signup 페이지 헤더 수정

src/main/java/com/multi/controller/MainController.java, src/main/resources/static/assets/ezocss/centercss.css, src/main/resources/templates/center.html
- 약 디테일 페이지로 이동 기능 구현
- 현재 controller (/mymedi)로 선택된 아이템이 보내짐
- center.html
- getname(item) method 및 검색결과 테이블 `a 태그` 추가
- MainController.java (/mymedi)
- Parameter로 `String item` 추가  
- `MainController`로 `item`이 보내지는 테스트 완료
---
관련 Issue: #44
=> ✨🚧약 디테일 페이지로 이동 기능 구현 중 item을 controller로 보내기 완료

src/main/java/com/multi/controller/MainController.java, src/main/resources/templates/center.html, src/main/resources/templates/medidetail.html
- medidetail 정보 출력
(스크린샷 추가 가능)
- 검색 결과 클릭 시 디테일 페이지로 이동
- 디테일 페이지에 정보 출력
테스트 유무
---
관련 Issue:
#44
=> 📦 medidetail 정보 출력 기능 구현

src/main/java/com/multi/controller/AJAXController.java, src/main/java/com/multi/controller/MainController.java, src/main/java/com/multi/frame/Util.java, src/main/java/com/multi/vo/MfVo.java, src/main/resources/application.properties, src/main/resources/templates/center.html
- OCR 이미지 업로드 창 기능 구현 중 코드 공유
(스크린샷 추가 가능)
테스트 유무
---
관련 Issue: #40
=> 🚧 OCR 이미지 업로드 창 기능 구현 중 코드 공유

src/main/java/com/multi/controller/AJAXController.java, src/main/java/com/multi/controller/MainController.java, src/main/java/com/multi/frame/Util.java, src/main/resources/templates/center.html
- ocr 창 사진 업로드로 검색 기능 구현
- `center.html`에서 `ocraddimpl`로 `mf(input)`을 `submit`으로 보낸다.
- MainController.java의 `ocraddimpl`
1. `MfVo`에 담긴 `mf`를 받아서 미리 소환해둔 `userdir`로 `Util.saveFile`를 이용해  보낸다.
- 사진이 img>box 폴더에 저장된다.
2.  boxocr로 해당 mf(imgname)을 보낸다.
3.  boxocr에서 받은 JSON(object)값을 parsing해서 약곽 이름만 뽑아서 Model에 담아 화면으로 가져간다.
4. center.html에서 받은 약곽이름을 검색창 input에 th:value로 뿌려준다.
- JSON parsing 테스트 완료 (`ocraddimpl`)
---
관련 Issue: #40
=> ✨ ocr box 스캔 기능 구현(사진 업로드) 완료

src/main/java/com/multi/controller/AJAXController.java, src/main/java/com/multi/mybatis/mymedimapper.xml, src/main/java/com/multi/vo/MymediVo.java, src/main/resources/templates/medidetail.html, src/main/resources/templates/mymedi.html, src/test/java/com/multi/mymedi/MymediInsertTests.java
- mymedi에 추가 버튼 기능 구현
(스크린샷 추가 가능)
- 디테일 페이지에서 추가버튼 클릭 시 mymedi에 추가
- mymedi에 image 출력
테스트 유무
---
관련 Issue:
#64
=> 📦 mymedi 추가 기능 구현

src/main/java/com/multi/biz/DashBiz.java, src/main/java/com/multi/controller/MainController.java, src/main/java/com/multi/mapper/DashMapper.java, src/main/java/com/multi/mybatis/dashmapper.xml, src/main/resources/templates/dashboard.html
Dashboard 카드에 총 스캔된 약들의 양 가져오기
DashMapper.java / DashBiz.java / dashmapper.xml 추가
(Dashboard에 추가할 기능들은 여기에 작업해주시면 될 것 같습니다.)
Dashboard 카드에 구현되는지 테스트 완료
---
관련 Issue: #65
=> ✨ 총 스캔된 약들의 양 가져오기 구현

src/main/java/com/multi/controller/AJAXController.java, src/main/java/com/multi/controller/MainController.java, src/main/java/com/multi/restapi/DataAPI2.java, src/main/java/com/multi/restapi/DataAPI3.java, src/main/resources/templates/center.html
분류 검색 기능 구현
테스트 유무
---
관련 Issue: #39
=> ✨ 분류 검색 기능 추가

src/main/java/com/multi/biz/SlistBiz.java, src/main/java/com/multi/controller/MainController.java, src/main/java/com/multi/mapper/SlistMapper.java, src/main/java/com/multi/mybatis/slistmapper.xml, src/main/java/com/multi/vo/SlistVo.java, src/test/java/com/multi/slist/SlistInsertboxTests.java, src/test/java/com/multi/slist/SlistSelectTheOneTests.java
- 메인 페이지 ocr box 사진 업로드로 검색하기 기능 구현
- SlistVo: ocrbox 함수를 위한 constructor 생성
- slistmapper.xml: insertbox와 selecttheone 함수의 sql 구문 정의
- SlistMapper와 SlistBiz에서 위의 두 함수 생성
- MainController의 addocrimple
1. 사진 저장
2. ocrbox 호출 및 결과값 화면으로 보내기
3. DB 스캔내역 및 스캔약 tbl에 정보 저장
- SlistInsertBoxTests.java
- insertbox 함수 테스트 완료 
- SlistSelectTheOneTests.java
- selecttheone 함수 테스트 완료 
---
관련 Issue: #40 
Co-Authored-By: qwaszx357 <94533219+qwaszx357@users.noreply.github.com>
=> ✨ 메인 페이지 ocr 창 기능 구현 완료

src/main/java/com/multi/controller/MainController.java, src/main/java/com/multi/mybatis/usersmapper.xml, src/main/resources/templates/profile.html
profile update
테스트 유무
---
관련 Issue: #71
=> ✨ profile update

src/main/resources/templates/pdetail.html
처방약에 약 이름 클릭 시 해당 약의 디테일로 넘어감
테스트 유무
---
관련 Issue: #112
=> ✨ 처방약 기능 구현

src/main/resources/templates/medidetail.html
- medidetail에 부작용 출력
(스크린샷 추가 가능)
- 약의 부작용, 관련 약 출력하기
테스트 유무
---
관련 Issue:
#121
=> 📦 medidetail 부작용 출력

src/main/resources/templates/index.html
- 유저 타입에 따라 navbar를 다르게 출력
(스크린샷 추가 가능)
- 유저로 로그인 시 '마이페이지'
- 관리자로 로그인 시 '관리자페이지'
테스트 유무
---
관련 Issue:
#118
=> ✨ utype에 따른 navbar 변경

src/main/java/com/multi/controller/AJAXController.java, src/main/java/com/multi/controller/MainController.java, src/main/java/com/multi/vo/PlistVo.java, src/main/resources/templates/padd.html
1. input 추가버튼 생성
2. 처방내역 정보 AJAXController로 보내기 (배열 보내기)
3. 해당 컨트롤러에서 DB에 정보 저장하기
4. 화면 리로드하기
5. 구현되어 있었던 OCR 기능 조정하기
6. UX 업데이트하기
7. 페이지 정돈하기
- 처방내역 추가 페이지 value null일 때 msg 기능을 구현 안함
- AJAXController.java
- plistaddimpl로 처방내역 정보를 DB에 넣음
- padd.html
- 화면 UI 구현 및 input 추가 등의 기능 구현  
- 입력된 처방정보 DB 저장 테스트 완료
---
Closes: #49
=> ✨🗑️ 처방내역 추가 기능 구현 완료 및 처방내역 추가 페이지 정리

src/main/java/com/multi/controller/AJAXController.java, src/main/resources/templates/medidetail.html
- medidetail.html에 주의사항 강조
(스크린샷 추가 가능)
- 주의사항에서 특정 단어에 강조효과 적용
테스트 유무
---
관련 Issue:
#125
=> ✨ medidetail에 정규표현식 적용

src/main/resources/static/assets/ezocss/centercss.css, src/main/resources/templates/center.html
검색 결과 테이블 수정
(스크린샷 추가 가능)
- 테이블 안에 글자 겹치지 않게 수정
- 효능 글자 수 제한
- 테이블 스크롤바 없애기
테스트 유무
---
관련 Issue:
#84
=> 💄 검색 결과 테이블 UI 정리

src/main/java/com/multi/controller/AJAXController.java, src/main/java/com/multi/controller/MainController.java, src/main/java/com/multi/mapper/UsersMapper.java, src/main/java/com/multi/mybatis/usersmapper.xml, src/main/resources/templates/signup.html
- 회원가입 페이지 정리
(스크린샷 추가 가능)
- null값 input에 메세지 출력
- label 추가
- 페이지 정리
테스트 유무
---
관련 Issue:
#143
=> ✨ 회원가입 시 null값 input에 메세지 출력

src/main/java/com/multi/controller/MainController.java, src/main/java/com/multi/controller/MypageController.java, src/main/resources/templates/center.html, src/main/resources/templates/index.html, src/main/resources/templates/mymedi.html, src/main/resources/templates/mypage/profile.html, src/main/resources/templates/signin.html
(스크린샷 추가 가능)
테스트 유무
---
Closes: #56 #76 #109 #141 #144 #145
=> 🎨 화면 마무리 정리1
